
TYPE_CHAT = 1
TYPE_EMAIL = 2
TYPE_STREAM = 3
TYPE_FILE = 4
TYPE_VOIP = 5
TYPE_P2P = 6

APP_AIM = 1
APP_EMAIL = 2
APP_FACEBOOK = 3
APP_FTP = 4
APP_GMAIL = 5
APP_HANGOUTS = 6
APP_ICQ = 7
APP_NETFLIX = 8
APP_SCP = 9
APP_SFTP = 10
APP_SKYPE = 11
APP_SPOTIFY = 12
APP_VIMEO = 13
APP_BUSTER = 14
APP_YOUTUBE = 15
APP_BITTORRENT = 16

TYPES = {
    'AIMchat1.pcapng': (0, TYPE_CHAT, APP_AIM),
    'AIMchat2.pcapng': (0, TYPE_CHAT, APP_AIM),
    'aim_chat_3a.pcap': (0, TYPE_CHAT, APP_AIM),
    'aim_chat_3b.pcap': (0, TYPE_CHAT, APP_AIM),
    'email1a.pcap': (0, TYPE_EMAIL, APP_EMAIL),
    'email1b.pcap': (0, TYPE_EMAIL, APP_EMAIL),
    'email2a.pcap': (0, TYPE_EMAIL, APP_EMAIL),
    'email2b.pcap': (0, TYPE_EMAIL, APP_EMAIL),
    'facebookchat1.pcapng': (0, TYPE_CHAT, APP_FACEBOOK),
    'facebookchat2.pcapng': (0, TYPE_CHAT, APP_FACEBOOK),
    'facebookchat3.pcapng': (0, TYPE_CHAT, APP_FACEBOOK),
    'facebook_audio1a.pcap': (0, TYPE_VOIP, APP_FACEBOOK),
    'facebook_audio1b.pcapng': (0, TYPE_VOIP, APP_FACEBOOK),
    'facebook_audio2a.pcap': (0, TYPE_VOIP, APP_FACEBOOK),
    'facebook_audio2b.pcapng': (0, TYPE_VOIP, APP_FACEBOOK),
    'facebook_audio3.pcapng': (0, TYPE_VOIP, APP_FACEBOOK),
    'facebook_audio4.pcapng': (0, TYPE_VOIP, APP_FACEBOOK),
    'facebook_chat_4a.pcap': (0, TYPE_CHAT, APP_FACEBOOK),
    'facebook_chat_4b.pcap': (0, TYPE_CHAT, APP_FACEBOOK),
    'facebook_video1a.pcap': (0, TYPE_VOIP, APP_FACEBOOK),
    'facebook_video1b.pcapng': (0, TYPE_VOIP, APP_FACEBOOK),
    'facebook_video2a.pcap': (0, TYPE_VOIP, APP_FACEBOOK),
    'facebook_video2b.pcapng': (0, TYPE_VOIP, APP_FACEBOOK),
    'ftps_down_1a.pcap': (0, TYPE_FILE, APP_FTP),
    'ftps_down_1b.pcap': (0, TYPE_FILE, APP_FTP),
    'ftps_up_2a.pcap': (0, TYPE_FILE, APP_FTP),
    'ftps_up_2b.pcap': (0, TYPE_FILE, APP_FTP),
    'gmailchat1.pcapng': (0, TYPE_CHAT, APP_GMAIL),
    'gmailchat2.pcapng': (0, TYPE_CHAT, APP_GMAIL),
    'gmailchat3.pcapng': (0, TYPE_CHAT, APP_GMAIL),
    'hangouts_audio1a.pcap': (0, TYPE_VOIP, APP_HANGOUTS),
    'hangouts_audio1b.pcapng': (0, TYPE_VOIP, APP_HANGOUTS),
    'hangouts_audio2a.pcap': (0, TYPE_VOIP, APP_HANGOUTS),
    'hangouts_audio2b.pcapng': (0, TYPE_VOIP, APP_HANGOUTS),
    'hangouts_audio3.pcapng': (0, TYPE_VOIP, APP_HANGOUTS),
    'hangouts_audio4.pcapng': (0, TYPE_VOIP, APP_HANGOUTS),
    'hangouts_chat_4a.pcap': (0, TYPE_CHAT, APP_HANGOUTS),
    'hangouts_video1b.pcapng': (0, TYPE_CHAT, APP_HANGOUTS),
    'hangouts_video2a.pcap': (0, TYPE_VOIP, APP_HANGOUTS),
    'hangouts_video2b.pcapng': (0, TYPE_VOIP, APP_HANGOUTS),
    'hangout_chat_4b.pcap': (0, TYPE_CHAT, APP_HANGOUTS),
    'ICQchat1.pcapng': (0, TYPE_CHAT, APP_ICQ),
    'ICQchat2.pcapng': (0, TYPE_CHAT, APP_ICQ),
    'icq_chat_3a.pcap': (0, TYPE_CHAT, APP_ICQ),
    'icq_chat_3b.pcap': (0, TYPE_CHAT, APP_ICQ),
    'netflix1.pcap': (0, TYPE_STREAM, APP_NETFLIX),
    'netflix2.pcap': (0, TYPE_STREAM, APP_NETFLIX),
    'netflix3.pcap': (0, TYPE_STREAM, APP_NETFLIX),
    'netflix4.pcap': (0, TYPE_STREAM, APP_NETFLIX),
    'scp1.pcapng': (0, TYPE_FILE, APP_SCP),
    'scpDown1.pcap': (0, TYPE_FILE, APP_SCP),
    'scpDown2.pcap': (0, TYPE_FILE, APP_SCP),
    'scpDown3.pcap': (0, TYPE_FILE, APP_SCP),
    'scpDown4.pcap': (0, TYPE_FILE, APP_SCP),
    'scpDown5.pcap': (0, TYPE_FILE, APP_SCP),
    'scpDown6.pcap': (0, TYPE_FILE, APP_SCP),
    'scpUp1.pcap': (0, TYPE_FILE, APP_SCP),
    'scpUp2.pcap': (0, TYPE_FILE, APP_SCP),
    'scpUp3.pcap': (0, TYPE_FILE, APP_SCP),
    'scpUp5.pcap': (0, TYPE_FILE, APP_SCP),
    'scpUp6.pcap': (0, TYPE_FILE, APP_SCP),
    'sftp1.pcapng': (0, TYPE_FILE, APP_SFTP),
    'sftpDown1.pcap': (0, TYPE_FILE, APP_SFTP),
    'sftpDown2.pcap': (0, TYPE_FILE, APP_SFTP),
    'sftpUp1.pcap': (0, TYPE_FILE, APP_SFTP),
    'sftp_down_3a.pcap': (0, TYPE_FILE, APP_SFTP),
    'sftp_down_3b.pcap': (0, TYPE_FILE, APP_SFTP),
    'sftp_up_2a.pcap': (0, TYPE_FILE, APP_SFTP),
    'sftp_up_2b.pcap': (0, TYPE_FILE, APP_SFTP),
    'skype_audio1a.pcap': (0, TYPE_VOIP, APP_SKYPE),
    'skype_audio1b.pcapng': (0, TYPE_VOIP, APP_SKYPE),
    'skype_audio2a.pcap': (0, TYPE_VOIP, APP_SKYPE),
    'skype_audio2b.pcapng': (0, TYPE_VOIP, APP_SKYPE),
    'skype_audio3.pcapng': (0, TYPE_VOIP, APP_SKYPE),
    'skype_audio4.pcapng': (0, TYPE_VOIP, APP_SKYPE),
    'skype_chat1a.pcap': (0, TYPE_CHAT, APP_SKYPE),
    'skype_chat1b.pcap': (0, TYPE_CHAT, APP_SKYPE),
    'skype_file1.pcap': (0, TYPE_FILE, APP_SKYPE),
    'skype_file2.pcap': (0, TYPE_FILE, APP_SKYPE),
    'skype_file3.pcap': (0, TYPE_FILE, APP_SKYPE),
    'skype_file4.pcapng': (0, TYPE_FILE, APP_SKYPE),
    'skype_file5.pcapng': (0, TYPE_FILE, APP_SKYPE),
    'skype_file6.pcapng': (0, TYPE_FILE, APP_SKYPE),
    'skype_file7.pcapng': (0, TYPE_FILE, APP_SKYPE),
    'skype_file8.pcapng': (0, TYPE_FILE, APP_SKYPE),
    'skype_video1a.pcap': (0, TYPE_VOIP, APP_SKYPE),
    'skype_video1b.pcapng': (0, TYPE_VOIP, APP_SKYPE),
    'skype_video2a.pcap': (0, TYPE_VOIP, APP_SKYPE),
    'skype_video2b.pcapng': (0, TYPE_VOIP, APP_SKYPE),
    'spotify1.pcap': (0, TYPE_STREAM, APP_SPOTIFY),
    'spotify2.pcap': (0, TYPE_STREAM, APP_SPOTIFY),
    'spotify3.pcap': (0, TYPE_STREAM, APP_SPOTIFY),
    'spotify4.pcap': (0, TYPE_STREAM, APP_SPOTIFY),
    'vimeo1.pcap': (0, TYPE_STREAM, APP_VIMEO),
    'vimeo2.pcap': (0, TYPE_STREAM, APP_VIMEO),
    'vimeo3.pcap': (0, TYPE_STREAM, APP_VIMEO),
    'vimeo4.pcap': (0, TYPE_STREAM, APP_VIMEO),
    'voipbuster1b.pcapng': (0, TYPE_VOIP, APP_BUSTER),
    'voipbuster2b.pcapng': (0, TYPE_VOIP, APP_BUSTER),
    'voipbuster3b.pcapng': (0, TYPE_VOIP, APP_BUSTER),
    'voipbuster_4a.pcap': (0, TYPE_VOIP, APP_BUSTER),
    'voipbuster_4b.pcap': (0, TYPE_VOIP, APP_BUSTER),
    'youtube1.pcap': (0, TYPE_STREAM, APP_YOUTUBE),
    'youtube2.pcap': (0, TYPE_STREAM, APP_YOUTUBE),
    'youtube3.pcap': (0, TYPE_STREAM, APP_YOUTUBE),
    'youtube4.pcap': (0, TYPE_STREAM, APP_YOUTUBE),
    'youtube5.pcap': (0, TYPE_STREAM, APP_YOUTUBE),
    'youtube6.pcap': (0, TYPE_STREAM, APP_YOUTUBE),
    'youtubeHTML5_1.pcap': (0, TYPE_STREAM, APP_YOUTUBE),
    'vpn_aim_chat1a.pcap': (1, TYPE_CHAT, APP_AIM),
    'vpn_aim_chat1b.pcap': (1, TYPE_CHAT, APP_AIM),
    'vpn_bittorrent.pcap': (1, TYPE_P2P, APP_BITTORRENT),
    'vpn_email2a.pcap': (1, APP_EMAIL, APP_EMAIL),
    'vpn_email2b.pcap': (1, APP_EMAIL, APP_EMAIL),
    'vpn_facebook_audio2.pcap': (1, TYPE_VOIP, APP_FACEBOOK),
    'vpn_facebook_chat1a.pcap': (1, TYPE_CHAT, APP_FACEBOOK),
    'vpn_facebook_chat1b.pcap': (1, TYPE_CHAT, APP_FACEBOOK),
    'vpn_ftps_A.pcap': (1, TYPE_FILE, APP_FTP),
    'vpn_ftps_B.pcap': (1, TYPE_FILE, APP_FTP),
    'vpn_hangouts_audio1.pcap': (1, TYPE_VOIP, APP_HANGOUTS),
    'vpn_hangouts_audio2.pcap': (1, TYPE_VOIP, APP_HANGOUTS),
    'vpn_hangouts_chat1a.pcap': (1, TYPE_CHAT, APP_HANGOUTS),
    'vpn_hangouts_chat1b.pcap': (1, TYPE_CHAT, APP_HANGOUTS),
    'vpn_icq_chat1a.pcap': (1, TYPE_CHAT, APP_ICQ),
    'vpn_icq_chat1b.pcap': (1, TYPE_CHAT, APP_ICQ),
    'vpn_netflix_A.pcap': (1, TYPE_STREAM, APP_ICQ),
    'vpn_sftp_A.pcap': (1, TYPE_FILE, APP_SFTP),
    'vpn_sftp_B.pcap': (1, TYPE_FILE, APP_SFTP),
    'vpn_skype_audio1.pcap': (1, TYPE_VOIP, APP_SKYPE),
    'vpn_skype_audio2.pcap': (1, TYPE_VOIP, APP_SKYPE),
    'vpn_skype_chat1a.pcap': (1, TYPE_CHAT, APP_SKYPE),
    'vpn_skype_chat1b.pcap': (1, TYPE_CHAT, APP_SKYPE),
    'vpn_skype_files1a.pcap': (1, TYPE_FILE, APP_SKYPE),
    'vpn_skype_files1b.pcap': (1, TYPE_FILE, APP_SKYPE),
    'vpn_spotify_A.pcap': (1, TYPE_STREAM, APP_SPOTIFY),
    'vpn_vimeo_A.pcap': (1, TYPE_STREAM, APP_VIMEO),
    'vpn_vimeo_B.pcap': (1, TYPE_STREAM, APP_VIMEO),
    'vpn_voipbuster1a.pcap': (1, TYPE_VOIP, APP_BUSTER),
    'vpn_voipbuster1b.pcap': (1, TYPE_VOIP, APP_BUSTER),
    'vpn_youtube_A.pcap': (1, TYPE_STREAM, APP_YOUTUBE),
}
